# -*- coding: utf-8 -*-
"""Fashion_MNIST.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P6PiJBgOcvYnNf1St4rtCB-305e7utMo
"""

import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
import tensorflow as tf
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K

from keras.callbacks import ModelCheckpoint

!rm -rf ./logs/

# Commented out IPython magic to ensure Python compatibility.
%load_ext tensorboard

# Model / data parameters
num_classes = 10
input_shape = (28, 28, 1)

